apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-b
  namespace: app-ab
  labels:
    app: app-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-b
  template:
    metadata:
      labels:
        app: app-b
    spec:
      containers:
      - name: app-b-container
        image: app-b:0.0.1 # Image pulled from localhost
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        resources:
          limits:
            memory: "100Mi"
            cpu: "150m"
          requests:
            memory: "50Mi"
            cpu: "100m"
