apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-a
  namespace: app-ab
  labels:
    app: app-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-a
  template:
    metadata:
      labels:
        app: app-a
    spec:
      containers:
      - name: app-a-container
        image: app-a:latest # Image pulled from localhost
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        resources:
          limits:
            memory: "100Mi"
            cpu: "150m"
          requests:
            memory: "50Mi"
            cpu: "100m"
      #   volumeMounts:
      #   - name: tls-cert
      #     mountPath: /etc/tls
      #     readOnly: true
      # volumes:
      # - name: tls-cert
      #   secret:
      #     secretName: app-a-tls
