apiVersion: v1
kind: Pod
metadata:
  name: dnsutils
  namespace: app-ab
spec:
  containers:
  - name: dnsutils
    image: busybox:1.28
    command:
      - sleep
      - "3600"
  restartPolicy: Always
