apiVersion: v1
kind: Service
metadata:
  name: app-b
  namespace: app-ab
  labels:
    app: app-b
spec:
  selector:
    app: app-b
  ports:
    - protocol: TCP
      port: 5000    # Exposes the service on port 5000
      targetPort: 5000 # Forwards traffic to container port 5000
  type: ClusterIP    # Internal service
